name: StashApp
options:
  deploymentTarget:
    iOS: "15.0"
targets:
  StashApp:
    type: application
    platform: iOS
    sources:
      - StashApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.doylerules.stash
        INFOPLIST_FILE: StashApp/Info.plist
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: StashApp/StashApp.entitlements
schemes:
  StashApp:
    build:
      targets:
        StashApp: all
