name: StashApp
options:
  deploymentTarget:
    iOS: "15.0" # Minimum iOS version
targets:
  StashApp:
    type: application
    platform: iOS
    sources:
      - StashApp
    settings:
      base:
        INFOPLIST_FILE: StashApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: org.doylerules.stash
        TARGETED_DEVICE_FAMILY: "1,2" # 1 = iPhone, 2 = iPad (universal)
        CODE_SIGN_ENTITLEMENTS: StashApp/StashApp.entitlements